"""add refresh tokens created_at

Revision ID: 9432c7fd15bd
Revises: bd1cb4ee5989
Create Date: 2026-09-04 10:04:19.002169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9432c7fd15bd'
down_revision: Union[str, Sequence[str], None] = 'bd1cb4ee5989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'created_at')
    # ### end Alembic commands ###
