"""add listing slug

Revision ID: c08e789f876c
Revises: f40de3b6e71b
Create Date: 2026-08-26 19:23:41.185532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08e789f876c'
down_revision: Union[str, Sequence[str], None] = 'f40de3b6e71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('slug', sa.String(length=80), nullable=False))
    op.create_unique_constraint(op.f('uq_listings_slug'), 'listings', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_listings_slug'), 'listings', type_='unique')
    op.drop_column('listings', 'slug')
    # ### end Alembic commands ###
