services:
  api:
    build:
      context: ../../api
      # Consider moving Dockerfile into build context
      dockerfile: ../docker/api/Dockerfile
      target: dev
    command: 
      - fastapi 
      - dev 
      - --host 
      - 0.0.0.0 
      - --port 
      - "8000"
    env_file:
      - ../../api/.env
    working_dir: /app
    volumes:
      # `:Z` - private SELinux label, `:z` - global
      - ../../api:/app:Z
    ports:
      - "127.0.0.1:8000:8000"

  web:
    build:
      context: ../../web
      dockerfile: ../docker/web/Dockerfile
    command:
      - npm
      - run 
      - dev 
      - -- 
      - --host 
      - 0.0.0.0
    working_dir: /app
    volumes:
      - ../../web:/app:Z
    ports:
      - "127.0.0.1:5173:5173"