[project]
name = "booking-api"
version = "0.1.0"
description = "Backend API for the booking application"
requires-python = ">=3.14"

dependencies = [
    "alembic>=1.19.1",
    "boto3>=1.43.73",
    "fastapi[standard]>=0.141.1",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.4",
    "python-slugify>=8.0.4",
    "sqlalchemy>=2.0.51",
]

[dependency-groups]
dev = [
    "moto[s3]>=5.2.2",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-env>=1.7.0",
    "ruff>=0.16.2",
    "typer>=0.27.1",
]

[project.scripts]
booking = "app.cli.main:app"

[tool.uv]
package = true

[tool.fastapi]
entrypoint = "app.main:app"

[tool.ruff]
line-length = 88
exclude = ["app/db/migrations/versions"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]

[tool.ruff.lint.isort]
known-first-party = ["app"]

[tool.pyright]
typeCheckingMode = "standard"

[tool.pytest.ini_options]
asyncio_mode = "auto"
env = [
    "APP_ENV=testing",

    "DB__HOST=db-test",
    "DB__NAME=booking_test",
    "DB__USER=booking_test",
    "DB__PASSWORD=booking_test",

    # Unset endpoint URL
    "U:S3__ENDPOINT_URL",
    "S3__ACCESS_KEY=booking_test",
    "S3__SECRET_KEY=booking_test",
    "S3__REGION=us-east-1",
    "S3__BUCKET=booking-test",
    "S3__PUBLIC_BASE_URL=http://test-storage",
    "AWS_ACCESS_KEY_ID=booking_test",
    "AWS_SECRET_ACCESS_KEY=booking_test",
    "AWS_DEFAULT_REGION=us-east-1"
]
